.travis.yml
utils/config_validator.py
utils/sqf_validator.py

This PR adds some basic validation and checking scripts from the [ACE Arma project template](https://github.com/acemod/arma-project-template), and the travis configuration for running the scripts.
The validation scripts check against the following items:
- sqf_validator.py - checks all .sqf files in the addons directory and checks for missing brackets, missing semi-colons.
- config_validator.py - checks all .hpp and .cpp files in the addons directory and checks for missing brackets.
The validation scripts contain a few differences compared to the ACE version;
- It does not check against tabs or indentation. I did not know what standards are used with the ALiVE project, so I have left that out for the time being.
Both scripts are written in a basic and rough format, but do their job well.

Add SQF and Config validation scripts

---

addons/mil_c2istar/fnc_taskHandlerSaveData.sqf

Task's `_data` was nil and with `sys_data` debug on I get this message:
```
2016/06/19, 12:57:11 Error in expression <...",_missionName] call ALIVE_fnc_dump;
_data call ALIVE_fnc_inspectHash;
};
i>
2016/06/19, 12:57:11   Error position: <_data call ALIVE_fnc_inspectHash;
};
i>
2016/06/19, 12:57:11   Error Undefined variable in expression: _data
2016/06/19, 12:57:11 File x\alive\addons\mil_C2ISTAR\fnc_taskHandlerSaveData.sqf, line 54
```

[mil_c2istar] Check for _data being nil

---

addons/ui/CfgFunctions.hpp
addons/ui/CfgPatches.hpp
addons/ui/config.cpp
addons/ui/fnc_copyFactionClasses.sqf

Adds a context menu item that copies the faction class names of selected objects to clipboard.

Add log faction classes in 3den context menu

---

addons/x_lib/script_macros.hpp

Fixes an error with Rapify (1.76.5.37)

Undefine LOG macro before redefining it

---

addons/sys_profile/fnc_profileSimulator.sqf

Some RHS vehicles were not returning any hitpoints for use when calculating virtualised damage. [(configfile >> "CfgVehicles" >> _vehicleClass >> "HitPoints"),0] call BIS_fnc_returnChildren; is a much slower method of getting the hitpoints but it seems to be more thorough and works on all RHS vehicles. This is only called when the original method doesn't work. 
This solves the "Undefined variable in expression: _randomhitpoint" error.

[sys_profile] Fixed hitpoints not detected for some RHS vehicles #286

---

addons/main/fnc_AI_Distributor.sqf

This pull updates ALIVE_fnc_AI_Distributor with the folllowing features:
- Dynamic detection of HCs
- Check if ACEX Headless module is active
- Refined start and stop checks
- Selectable distribution cycle
It also deprecates the function `ALIVE_fnc_isHC` *(\x_lib\functions\misc\fnc_isHC.sqf)* and calls to it that handled HCs with the old code: https://github.com/ALiVEOS/ALiVE.OS/blob/377869424bcd41e6c4b1e171377860ece50be9d2/addons/x_lib/preinit.sqf#L14

[MAIN] AI_Distributor

---

addons/mil_placement_custom/fnc_CMP.sqf

* Fixes issues seen in #471 
Test with devbuild from master:
<details>
<summary>Pre</summary>
0:40:48 Spawning Composition: [<null>,[10069.6,10396.8,0],0,"OPF_F"]
0:40:48 Error in expression < %1, expected %2, on index %3, in %4", [_par] call _fnc_getTypeName, [_x] call _>
0:40:48   Error position: <_par] call _fnc_getTypeName, [_x] call _>
0:40:48   Error Undefined variable in expression: _par
0:40:48 File A3\functions_f\Debug\fn_errorParamsType.sqf [BIS_fnc_errorParamsType], line 146
0:40:48 Error in expression <0) pushBack _position;
if (configName _config in _brokenCheckpoints) then {
_a>
0:40:48   Error position: <_config in _brokenCheckpoints) then {
_a>
0:40:48   Error Undefined variable in expression: _config
0:40:48 File …

[mil_placement_custom] Handle custom composition lookup to prevent init errors

---

addons/civ_placement/fnc_createRoadblock.sqf

- fixed description
- optimised one statment (no time for more)
- it was possible to return NIL, but ALiVE_fnc_INS_helpers need everytime an array, fixed

[createRoadblock] fixed nil return to array to fix an error

---

addons/mil_c2istar/tasks/fnc_taskRescue.sqf

_saver was a group, not an object
```
16:02:02 Error in expression <eep 1;
[_hostage] joinSilent _saver;
(group _saver) selectLeader _saver;
_tas>
16:02:02   Error position: <group _saver) selectLeader _saver;
_tas>
16:02:02   Error group: Typ Gruppe, erwartet Objekt
16:02:02 File \x\alive\addons\mil_C2ISTAR\tasks\fnc_taskRescue.sqf [ALiVE_fnc_taskRescue], line 2297
```

Error in rescue task

---

addons/sys_adminactions/fnc_adminActionsMenuDef.sqf
addons/x_lib/functions/misc/fnc_isServerAdmin.sqf

Fixed the problem with enableDebugConsole as an array and also reworked the admin action system.
Error:
```
18:40:49 Error in expression <onConfigValue ["enableDebugConsole",0]) > 0},
true
]
]
]
];
};
if (_menuName ==>
18:40:49   Error position: <> 0},
true
]
]
]
];
};
if (_menuName ==>
18:40:49   Error >: Typ Array, erwartet Zahl,Keine Zahl
18:40:49 File \x\alive\addons\sys_adminactions\fnc_adminActionsMenuDef.sqf [ALiVE_fnc_adminActionsMenuDef], line 2113
```

fixed enableDebugConsole as array && admin menu reworked

---

addons/main/fnc_aliveInit.sqf
addons/sys_profile/CfgVehicles.hpp
addons/sys_profile/fnc_getNearProfiles.sqf
addons/sys_profile/fnc_profile.sqf
addons/sys_profile/fnc_profileAttack.sqf
addons/sys_profile/fnc_profileCombatHandler.sqf
addons/sys_profile/fnc_profileEntity.sqf
addons/sys_profile/fnc_profileGetGoodSpawnPosition.sqf
addons/sys_profile/fnc_profileHandler.sqf
addons/sys_profile/fnc_profileSimulator.sqf
addons/sys_profile/fnc_profileSpawner.sqf
addons/sys_profile/fnc_profileSystem.sqf
addons/sys_profile/fnc_profileVehicle.sqf
addons/x_lib/functions/data/fnc_spacialGrid.sqf
addons/x_lib/functions/oop/fnc_BaseClassHash.sqf

Finding profiles within a radius of an area is currently a costly operation, one that involves a massive loop over all profiles. This pull request will integrate a uniform grid as a spacial partitioning structure in order to introduce a broad-phase form of collision detection that will allow us to quickly reduce our sample of profiles which will be run through the distance command.
<hr>
Any module that modifies a profile's position, must call directly to the `position` method of either the profileEntity or profileVehicle class. These methods handle the updating of the object's position inside the uniform grid.
<hr>
Here is the debug console results of two queries, using the same set of sample data.
Original:
```
Result:
1.89036 ms
Cycles:
529/10000
Code:
[getPos player, 1000] call …
```

[sys_profile] Integrate spacial grid for profiles, getNearProfiles

---

addons/x_lib/functions/config/fnc_getArtyMagazineType.sqf
addons/x_lib/functions/config/fnc_getArtyRounds.sqf

Artillery ammo is now grabbed from the main turret's magazine array in the vehicle config file. This change ensures the correct shells are returned for each faction's artillery pieces. Note, the tanks DLC introduced separate shells for OPFOR artillery pieces.

[sup_combatsupport] Fixes ALiVEOS/ALiVE.OS#523

---

addons/fnc_analysis/fnc_battlefieldAnalysis.sqf
addons/mil_c2istar/tasks/fnc_taskMilAssault.sqf
addons/mil_c2istar/tasks/fnc_taskMilDefence.sqf
addons/mil_c2istar/utils/fnc_taskGetSideCluster.sqf
addons/mil_placement_custom/CfgVehicles.hpp
addons/mil_placement_custom/fnc_CMP.sqf
addons/mil_placement_custom/stringtable.xml

-New module parameter added to custom military objectives
--Allows mission maker to disable C2ISTAR MilAssault/MilDefend player tasking
on custom military objectives
-New global variable ALIVE_clustersMilCustom to track custom military
objectives
--Allow access to custom military objective clusters without
coupling the code too much
(Hacky) fix for #542

[mil_c2istar] Toggle tasking on custom mil obj

---

addons/mil_opcom/fnc_OPCOM.sqf
addons/mil_opcom/opcom.fsm
addons/mil_opcom/tacom.fsm

Previously, the danger value for an objective was set to the value of _all_ known entities. This change fixes it so the danger value of an objective is only the number of enemies within a radius around the objective.
This PR also brings some performance improvements to enemy scanning.

[mil_opcom] Fix enemy scanning returning wrong results

---

addons/x_lib/functions/map/fnc_isHouseEnterable.sqf

A mission maker may want to use ALiVE's CQB spawner, but want to blacklist some buildings that are enterable from spawning units.
Example use:
in init.sqf
ALIVE_Building_Blacklist=["Land_bigwall1_arch","Land_loam_wall1_arch2"];
WIP because I am not convinced this is the best way/place to do this (use indexing blacklist instead? add a building blacklist text box to the module?), and blacklist might also be useful for civ spawn stuff

WIP: Blacklist buildings from CQB spawns

---

addons/x_lib/functions/units/fnc_isArmed.sqf

ALIVE_fnc_isArmed didn't consider dynamic loadouts in the case of helis

Fix ato not recognising dynamic loadout vehicles

---

addons/sys_player/playerData.hpp

Additional backpacks spawn on player restore previous state, and
probably other player state loads

Prevent additional backpacks

---

addons/sys_logistics/fnc_logistics.sqf

Issue reference #708 
From what I can tell, dropObject should only ever be assigned to a player once carrying an object. 
- When evaluating a condition for an addAction, three objects are passed. In this instance, we use `_target` to evaluate if the player is Alive, in a vehicle or currently carrying an object. 
- When passed, `_target` represents the player OR the players current vehicle if present. 
- Issue appears to be this statement where we evaluate if the vehicle of the target (the vehicle itself) is equal to the target (again, the vehicle).  This will always return `true` if the player is in a vehicle:
```sqf
{vehicle _target == _target}
```
- Easy fix, addAction passes `_originalTarget` which will always represent the target in which the addAction is being applied to (player).

Fixed Drop Object addAction

---

addons/amb_civ_placement/fnc_AMBCP.sqf
addons/civ_placement/fnc_CP.sqf
addons/mil_placement/fnc_MP.sqf

- When CP/MP/AMBCP placements cannot find a location within a TAOR it will now debug the TAOR name to assist with troubleshooting.
Example:
```sqf
ALIVE AMBCP - Warning no locations found for placement, you need to include civilian locations within the TAOR marker: ["test_amb_civ_marker"]
ALIVE MP [OPF_F] - Warning no locations found for placement, you need to include military locations within the TAOR marker: ["test_mp_marker"]
ALIVE CP [OPF_F] - Warning no locations found for placement, you need to inclcude civilian locations within the TAOR marker: ["test_cp_marker"]
```

CP/MP Debug Improvement

---

addons/sys_profile/fnc_profileEntity.sqf

#720 
In fnc_profileEntity.sqf, under the "spawn" case, the profile waypoints were created before the vehicle assignments. Due to this, mechanized and armored profiles get stuck right after spawning, because they have a move waypoint before the entire crew is inside the vehicle.
All I did was change the order in which these two functions execute. Now waypoints are created after vehicle assignments. All vehicles now move normally after spawning. It's a very simple fix, shouldn't affect anything else.

Fixed mechanized/armored units not moving after spawning [issue 720]

---

addons/sys_marker/fnc_marker.sqf

#718 
**Summary:**
Control Event Handlers are stackable and are processed in reverse order (i.e. last added: processed first, first added: processed last). In this instance, ALiVEs EH's are processed first as they're declared last. Issue is that as soon as one of the processed event handlers returns a `true` response, no further stacked executions take place.
**Replication Code**
```sqf
fnc_test1 = {
diag_log "[ALiVE-TEST] - Test 1 - Success!";
_result = true;
_result;
};
fnc_test2 = {
diag_log "[ALiVE-TEST] - Test 2 - Success!";
};
_control = finddisplay 12 displayctrl 51; 
_control ctrladdeventhandler ["mousebuttonclick","[] call fnc_test2"];
_control ctrladdeventhandler ["mousebuttonclick","[] call fnc_test1"]; 
```
**Replication Output**
```
17:37:23 "[ALiVE-TEST] - Test 1 - Success!" …
```

[sys_marker] Fix for stacked Ctrl EventHandlers

---

addons/mil_logistics/fnc_ML.sqf
addons/mil_opcom/opcom.fsm

Opcom includes logistic trucks, helicopters and player added entities
to the reinforcement calculation. This would return a negative request
for the logistics, which broke both opcom and the logistic module.
Sanitized the diff calculation at opcom.fsm, excess units are ignored.

[opcom] Logistics fix, fixes issue #765

---

addons/mil_logistics/fnc_ML.sqf

The logistic fix introduced on PR #766 did not account for player
logistics requests.

[mil_logistics] Restrict the logistics sanitization to opcom

---

addons/sys_logistics/fnc_logistics.sqf

Fix for a crash in sys_log
When 
[nil,"removeActions", anObject] call ALIVE_fnc_logistics;
is run, 
if !(hasInterface) exitwith {
[[_logic, "removeActionsTerm", _args],"ALIVE_fnc_logistics", owner _args, false] call BIS_fnc_MP;
};
is called forever serverside until the server crashes.
What causes the nil call to occur in the first place hasn't been identified, but this should address both a nil call, and other potential runaway.

Replace self-referencing BIS_fnc_MP call to address a crash

---

addons/x_lib/functions/markers/fnc_validateLocations.sqf

Candidate IED objects in blacklisted areas wouldn't be excluded.

[x_lib] Fixes IED blacklist #748

---

addons/mil_opcom/fnc_OPCOM.sqf
addons/sys_profile/fnc_profileWaypointToWaypoint.sqf

The OPCOM changes are just bugfixes. The waypoints are a bit different. I noticed that the waypoints created by ALiVE tends to make vehicles drive off roads for no reason. 
https://community.bistudio.com/wiki/addWaypoint
The addWaypoint function takes 4 args in addition to the group, one of which is radius. You'd think normally that radius would be the distance you have to be from the wp for it to be completed, but it actually randomizes the waypoint. Instead of doing this for vehicles, we find the closest road and set radius to -1 (for exact placement).

Fix 2 OPCOM bugs, snap waypoints to roads

---

addons/mil_ato/fnc_ATO.sqf
addons/sup_combatsupport/fnc_combatSupport.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_ExecuteMission.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_supportAdd.sqf

Added the ability to sync groups of artillery units rather than single. Also, groups of more or less than 3 use proper number of rounds. 
To use properly: 
Create an artillery group of (e.g. 4 units)
In one of the units INIT (preferably the leader)- add proper code for CS_TYPE and CS_CALLSIGN (optionally)
Sync that unit (again preferably the leader) directly to Player CS Module
Should only show as single line entry in player UI as Callsign or GroupID
Any requests will use up to entire group to expend the correct number of rounds selected.
Also added quick fix for Issue #780 while I was meddling in this area.

Artillery fixes

---

addons/mil_command/fnc_ambientMovement.sqf
addons/mil_command/fnc_garrison.sqf
addons/mil_intelligence/fnc_G2.sqf
addons/mil_opcom/fnc_OPCOM.sqf

This is an attempt to reduce the effects of the race condition.
Since units profiles are unregistered upon death by an event handler, opcom and intelligence may try to act upon already unregistered profiles.
This would generate an error spam on fnc_G2.sqf and also rarely stall opcom.
Since the profiles are returned as new instances, a workaround is to check if the returned value was null, otherwise it's pretty safe to go ahead.

Added isnil check on attempts to retrieve _profile

---

addons/mil_ato/fnc_ATO.sqf

Without the deleteAt, the resupplyList queue never actually shrinks and it will repeatedly stack replacement aircraft at the same spot.
(Will cause a full crash when a spawn source gets close enough and it tries to spawn 100+ aircraft at the same location)
Sidenote: Would you guys prefer separate PRs for unrelated bugfixes, or should I do all ~6 in one go?

[mil_ATO] Fix infinite resupply - Remove from resupplyList

---

addons/mil_opcom/fnc_OPCOM.sqf

- "Mechandized" only appears in these two instances, in all of the ALiVE code
- Move the check down below the `if (rtb and ATO available) exitWith ...` block to avoid interfering with that
- This way it won't end up creating a LAND waypoint for say, an armored profile
_See annotated (old) code below:_
```
private _ordersToRemove = [];
{
_x params ["_pos","_profileID","_objectiveID","_time"];
private _dead = isnil { [ALiVE_profileHandler,"getProfile", _profileID] call ALiVE_fnc_profileHandler };
private _timeout = (time - _time) > 3600;
if (_dead || { _timeout } || { _ProfileID == _ProfileIDInput }) then {
_ordersToRemove pushback _foreachindex;
//  ***************HERE***************
// It checks to see if there are any more orders for this objective, 
// but this one (in_x variable) …
```

[mil_OPCOM] Multiple bug fixes

---

addons/mil_command/fnc_ambush.sqf

Rather than waiting until 1800 seconds had passed since the code started, it would wait until 3600 seconds had passed since mission start. Any executions after 3600 seconds (an hour) would finish the timeout after a single "sleep 10" call, essentially immediately deleting the bombs.
New code ensures that the timeout period is `_timeout` (1800) since ambush start instead.

[mil_command] Fix fnc_ambush typo causing premature timeout

---

addons/sys_profile/fnc_profileWaypointToWaypoint.sqf

If vehicle waypoint radius isn't set to -1, they will be randomized and not follow the roads exactly.

Vehicle waypoints should always be exact

---

addons/sys_pathfinding/fnc_pathfindingGrid.sqf

to avoid error during water compression check if its a non-existent sector

[pathfinding] isnil check in getSector getSubSector
