addons/fnc_analysis/fnc_gridAnalysisActive.sqf

Fixes this error message:
```
17:21:44 Error in expression <ectorData];
if("active" in (_sectorData select 1)) then {
[_sector, "data", ["ac>
17:21:44   Error position: <select 1)) then {
[_sector, "data", ["ac>
17:21:44   Error Generic error in expression
17:21:44 File x\alive\addons\fnc_analysis\fnc_gridAnalysisActive.sqf, line 48
```

[fnc_analysis] Check whether _sectorData is an array

---

addons/sup_combatsupport/fnc_combatSupport.sqf
addons/x_lib/functions/config/fnc_sortCFGGroupsByFaction.sqf
addons/x_lib/functions/config/fnc_sortCFGGroupsBySide.sqf

Packing, moving and unpacking mortars is still very much broken (for all sides/factions as far as I have seen).

IND_F fixes (logistics tablet & mortars)

---

addons/sys_profile/fnc_profileGetDamageOutput.sqf
addons/sys_profile/fnc_profileSimulator.sqf

Fixes most remaining bugs with the new virtual combat system. Some may still remain, but testing yields good results so far.

Virtual combat enhancements

---

addons/sup_combatsupport/scripts/NEO_radio/fsms/transport.fsm

See comment by kju @ https://community.bistudio.com/wiki/deleteWaypoint

[SUP_TRANSPORT] Proper way to clear waypoints (fixes #71)

---

addons/sys_data/CfgVehicles.hpp
addons/sys_data/stringtable.xml
addons/sys_perf/fnc_perfMonitor.fsm

Add diag_activeScripts to perf monitor

---

addons/civ_placement/fnc_createRoadblock.sqf
addons/mil_convoy/fnc_startConvoy.sqf
addons/mil_logistics/fnc_ML.sqf
addons/mil_opcom/fnc_INS_helpers.sqf
addons/mil_opcom/insurgency.fsm
addons/mil_opcom/tacom.fsm
addons/sup_combatsupport/fnc_unpackMortar.sqf
addons/sup_combatsupport/scripts/NEO_radio/fsms/alivearty.fsm
addons/sup_combatsupport/scripts/NEO_radio/fsms/cas.fsm
addons/sup_combatsupport/scripts/NEO_radio/fsms/transport.fsm
addons/sys_profile/profileSimulator_v2.fsm
addons/sys_tour/fnc_tour.sqf

This PR will replace older BIS_fnc_dirTo calls with the newer alt. syntax of getDir

Optimization: Replace BIS_fnc_dirTo with getDir

---

addons/civ_placement/fnc_createRoadblock.sqf
addons/mil_convoy/fnc_startConvoy.sqf
addons/mil_ied/fnc_createBomber.sqf
addons/mil_opcom/insurgency.fsm

This PR will take care of a few BIS_fnc_selectRandom calls missed in #183

Optimization: Leftover BIS_fnc_selectRandom calls

---

addons/mil_ied/CfgVehicles.hpp

Make ALIVE IEDs visible for ACE3 minedetector

Make ALIVE IEDs visible for ACE3 minedetector

---

addons/main/fnc_AI_Distributor.sqf

* Handle calls where mode is `false` (Distribution set to Server in
module config)
* Does away with some tabs from copy/paste

[MAIN] AI_Distributor enhancements

---

addons/main/fnc_AI_Distributor.sqf

* Actually checks the value of `acex_headless_enabled`, not just presence.
* `AI_DISTRIBUTOR` value now properly checked with `isNull`, not just presence.
* Populate `AI_LOCALITIES` hash only if `_debug` is true.
Fixes #434 
**Tests without `(0/false)` ACEX Headless set to enabled:**
*Start*
```
18:56:31 ALIVE AI Distributor starting.
18:56:31 ALiVE AI Distributor detected no HCs, idling for 60 seconds.
18:57:32 ALiVE AI Distributor detected no HCs, idling for 60 seconds.
```
*Stop*
```
18:57:39 ALiVE AI Distributor shutting down (mode: false).
```
*Start with `<false>`*
```
18:57:55 ALiVE AI Distributor not enabled (mode: false).
```
*Double start*
```
18:58:13 ALIVE AI Distributor starting.
18:58:26 ALiVE AI Distributor already running !
```
**Tests with `(1/true)` ACEX Headless set to …

[main] Properly handle ACEX Headless, and other small optimizations

---

addons/mil_cqb/CfgVehicles.hpp
addons/mil_cqb/fnc_CQB.sqf
addons/mil_cqb/stringtable.xml

CQB Unit Blacklists 

---

addons/amb_civ_placement/fnc_AMBCP.sqf
addons/civ_placement/fnc_CP.sqf
addons/civ_placement/fnc_civClusterGeneration.sqf
addons/fnc_analysis/tests/test_appendClustersCiv.sqf
addons/fnc_analysis/tests/test_appendClustersMil.sqf
addons/fnc_analysis/tests/test_runMapAnalysis.sqf
addons/fnc_analysis/tests/test_sectorGrid.sqf
addons/main/CfgFunctions.hpp
addons/main/fnc_staticDataHandler.sqf
addons/mil_c2istar/fnc_C2ISTAR.sqf
addons/mil_cqb/fnc_CQB.sqf
addons/mil_placement/fnc_MP.sqf
addons/mil_placement/fnc_milClusterGeneration.sqf
addons/mil_placement_custom/fnc_CMP.sqf
addons/sup_player_resupply/fnc_PR.sqf
addons/sys_logistics/fnc_logistics.sqf
addons/sys_orbatcreator/fnc_orbatCreator.sqf
addons/sys_profile/fnc_profileSystem.sqf
addons/x_lib/functions/behaviour/fnc_groupGarrison.sqf

Overhauls the way staticData is loaded throughout various modules

staticData loading overhaul

---

addons/amb_civ_placement/CfgVehicles.hpp
addons/amb_civ_placement/stringtable.xml
addons/civ_placement/CfgVehicles.hpp
addons/civ_placement/stringtable.xml
addons/fnc_strategic/fnc_copyClusters.sqf
addons/mil_placement/CfgVehicles.hpp
addons/mil_placement/stringtable.xml

Addresses https://github.com/ALiVEOS/ALiVE.OS/issues/14

Placement Inverse Filtering

---

addons/amb_civ_command/fnc_civCommandRouter.sqf
addons/mil_c2istar/fnc_taskHandler.sqf
addons/mil_command/fnc_commandRouter.sqf

Fixed all managerHandles (objNull -> scriptNull)

---

addons/fnc_analysis/fnc_sectorFilterTerrain.sqf
addons/mil_c2istar/tasks/fnc_taskRescue.sqf
addons/sys_profile/fnc_profileEntity.sqf

addons/fnc_analysis/fnc_sectorFilterTerrain.sqf
```
15:54:27 Error in expression <all ALIVE_fnc_sector;
if("terrain" in (_sectorData select 1)) then {
_terrainDa>
15:54:27   Error position: <_sectorData select 1)) then {
_terrainDa>
15:54:27   Error Nicht definierte Variable in Ausdruck: _sectordata
15:54:27 File \x\alive\addons\fnc_analysis\fnc_sectorFilterTerrain.sqf [ALiVE_fnc_sectorFilterTerrain], line 1790
```
addons/sys_profile/fnc_profileEntity.sqf
```
14:42:20   Error position: <setRank _rank;
_unit setVariable ["ALi>
14:42:20   Error Fremdfehler: Unknown enum value: ""
14:42:20 File \x\alive\addons\sys_profile\fnc_profileEntity.sqf [ALiVE_fnc_profileEntity], line 2723
```

fixed two crashes

---

addons/sup_combatsupport/scripts/NEO_radio/fsms/cas.fsm
addons/sup_combatsupport/scripts/NEO_radio/fsms/transport.fsm
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/cas/fn_casBaseButton.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/transport/fn_transportBaseButton.sqf

[sup_combatsupport] Fix ETA on RTB Transport/CAS

---

addons/sup_combatsupport/fnc_combatSupport.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_getSitrep.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/fn_radioLbSelChanged.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/fn_radioMapEvent.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/fn_radioOnLoad.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/transport/fn_transportBaseButton.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/transport/fn_transportConfirmButton.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/transport/fn_transportConfirmButtonEnable.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/transport/fn_transportSmokeFoundButton.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/transport/fn_transportSmokeNotFoundButton.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/transport/fn_transportTaskLbSelChanged.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/ui/transport/fn_transportUnitLbSelChanged.sqf

-Adds feature #532. Hard coded max talk range to 50m, 2D distance, to match
max insertion height.

[sup_combatsupport] Talk to transport pilot outside

---

addons/mil_c2istar/fnc_taskHandler.sqf

[mil_c2istar] Ensure logic is grabbed before use

---

addons/mil_c2istar/fnc_taskHandler.sqf

[mil_c2istar] Fix task autogeneration params

---

addons/sup_combatsupport/scripts/NEO_radio/functions/ui/arty/fn_artyUnitLbSelChanged.sqf

[sup_combatsupport] Fix font for arty out of ammo

---

addons/mil_c2istar/fnc_C2MenuDef.sqf

Fix restrict combat support via items

---

addons/sys_player/playerData.hpp

To fix #621 
Need @TomTucka or other to confirm fixed before merge

Give acre radios by base class

---

addons/sys_acemenu/fnc_aceMenuCS.sqf

Fix running before NEO_radioLogic init

---

addons/x_lib/functions/config/fnc_configGetVehicleEmptyPositions.sqf

This should fix too many crew being spawned from the profile system.
Does not effect non-profile spawns

[x_lib] Fix extra crew spawns (profile system)

---

addons/sup_combatsupport/fnc_combatSupport.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_RespawnArtyAsset.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_RespawnCASAsset.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_RespawnTransportAsset.sqf
addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_supportAdd.sqf

[sup_combatsupport] Remove extra crew spawns (support)

---

addons/amb_civ_population/fnc_addCivilianActions.sqf
addons/amb_civ_population/fnc_civInteract.sqf
addons/amb_civ_population/fnc_questionHandler.sqf
addons/amb_civ_population/stringtable.xml

I changed all the text displayed to the players relative to civilian interaction to make it localizable. I also added Spanish translation.
There are a lot of strings repeated as I didn't want to change the structure of your scripts, in the future it could be replaced to make all strings unique and thus easier to maintain.
Let me know if you guys need any change with the naming convention.

feat(civPop): adds  localizable interactions with civilian population

---

addons/sys_logistics/fnc_setObjectCargo.sqf

Fix for ALiVE issue #695 
- Replaces ACRE unique ID's with Radio Base Class on persistence load.
- Tested with ACRE, CBA & ALiVE
- Tested with only CBA & ALiVE

Replace ACRE Radios with Base Classes on Persistence Load

---

addons/sys_player/playerData.hpp

Use private variables, name consistency with #699

Cleanup acre compatibility

---

addons/sys_player/playerData.hpp

For compatibility with mods that add ItemRadio to backpacks with no
inventory space
This is aimed to address #701

Add radio items ignoring inventory space limits

---

addons/sys_playeroptions/fnc_playeroptionsMenuDef.sqf
addons/sys_playeroptions/stringtable.xml

#605 
- Added the ability for a player to restore the marker store locally.
- Tested working in MP at time of PR

[sys_marker][sys_playeroptions] Add Restore Markers option to Player Menu

---

addons/mil_ato/fnc_ATO.sqf

[Fix] For issue #781  for _takeoff is null

---

addons/sup_multispawn/fnc_multispawn.sqf

Fix undefined error when using respawn in building

Fix respawn in building

---

addons/sys_profile/CfgFunctions.hpp
addons/sys_profile/fnc_findFilteredSafePos.sqf
addons/sys_profile/fnc_profileGetGoodSpawnPosition.sqf
addons/sys_profile/fnc_profileVehicle.sqf
addons/x_lib/config/CfgFunctions.hpp
addons/x_lib/functions/function_list.txt
addons/x_lib/functions/map/fnc_getSortedSeriesRoadPositions.sqf

I'm finally getting happy about how the spawning is turning out, I'm testing with massive motorised and mechanized units on Fallujah and Stratis, managed to reduce the number of explosions to a minimal.
I've kept the priority of spawn on roads, as the default were, and added a new heuristic search of safe positions for when there's no available road near, which is quite slow in crowded areas, although it seems ok. (Commonly you'll have wide clean spaces where vehicles can spawn and then it's quick.. the worst case scenario would be trying to spawn an army of trucks inside a forest, that would make it give up and spawn in the default position, also would be painfully slow.
The heuristic is just BIS_fnc_findSafeArea extended to allow for filtering static and dynamic objects...
I've also …

[sys_profile] Vehicle spawn fixes

---

addons/sys_pathfinding/fnc_pathfindingGrid.sqf

Fixes an enhanced pathfinding issue/error if a unit starts out of map bounds.

added check if units out of map sector boundaries
